# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='posts/')),
                ('tags', models.ManyToManyField(to='clone.tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.User')),
            ],
        ),
    ]
